version: "3.1"
services:
  postgres_server:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_SERVER_PORT}:${PG_SERVER_PORT}
  api_server:
    build: ./api_server
    restart: always
    env_file:
      - .env
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    volumes:
      - ./api_server:/usr/src/app
    depends_on:
      - postgres_server
  redis:
      image: redis
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - .env
    command: ["npm", "start"]
    ports:
      - ${FRONTEND_EXPOSE_PORT}:${FRONTEND_DEFAULT_PORT}
    expose:
      - ${FRONTEND_EXPOSE_PORT}
    stdin_open: true
    depends_on:
      - api_server
volumes:
  pgdata:
