version: "3.1"
services:
  postgres_server:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_SERVER_PORT}:${PG_SERVER_PORT}
  api_server:
    build: ./api_server
    restart: always
    env_file:
      - .env
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    volumes:
      - ./api_server:/usr/src/app
    depends_on:
      - postgres_server
  celery:
    restart: always
    build: ./api_server
    command: celery -A celery_app worker -l INFO
    env_file:
      - .env
    environment:
        - BROKER_URL=redis://redis/0
        - RESULT_BACKEND=redis://redis/1
    depends_on:
        - api_server
        - postgres_server
        - redis
  redis:
      image: redis
      ports:
        - "6379:6379"

volumes:
  pgdata:
