"""FundraiseStatus model added and M2M model for FundraiseStatusAssociation.

Revision ID: 04dff00d60a9
Revises: 865192039af4
Create Date: 2022-06-14 13:05:11.778501

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04dff00d60a9'
down_revision = '865192039af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundraise_statuses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraise_statuses_id'), 'fundraise_statuses', ['id'], unique=False)
    op.create_table('fundraise_status_association',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fundraise_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fundraise_id'], ['fundraisers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['fundraise_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraise_status_association_id'), 'fundraise_status_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundraise_status_association_id'), table_name='fundraise_status_association')
    op.drop_table('fundraise_status_association')
    op.drop_index(op.f('ix_fundraise_statuses_id'), table_name='fundraise_statuses')
    op.drop_table('fundraise_statuses')
    # ### end Alembic commands ###
