"""added donations

Revision ID: 16bffe05b09d
Revises: 258953be0f7e
Create Date: 2022-05-15 10:56:24.065518

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16bffe05b09d'
down_revision = '258953be0f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Donations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sender_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('recipient_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['Balances.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Balances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Donations_id'), 'Donations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Donations_id'), table_name='Donations')
    op.drop_table('Donations')
    # ### end Alembic commands ###
