"""Migration message.

Revision ID: 16f4b92ee598
Revises: a998fdfab5b3
Create Date: 2022-05-09 09:11:55.452651

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16f4b92ee598'
down_revision = 'a998fdfab5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Balances',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=2), default=0),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_Balances_id'), 'Balances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Balances_id'), table_name='Balances')
    op.drop_table('Balances')
    # ### end Alembic commands ###
