"""user_model_unique_fields_email_username

Revision ID: 1b26d8666aee
Revises: c024e48ebc32
Create Date: 2022-05-19 07:54:05.932811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b26d8666aee'
down_revision = 'c024e48ebc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CharityOrganisations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('organisation_email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CharityOrganisations_id'), 'CharityOrganisations', ['id'], unique=False)
    op.create_table('charity_user_association',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('charity_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('users_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['CharityOrganisations.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charity_user_association_id'), 'charity_user_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charity_user_association_id'), table_name='charity_user_association')
    op.drop_table('charity_user_association')
    op.drop_index(op.f('ix_CharityOrganisations_id'), table_name='CharityOrganisations')
    op.drop_table('CharityOrganisations')
    # ### end Alembic commands ###
