"""scale of refill

Revision ID: 258953be0f7e
Revises: d367b3e690be
Create Date: 2022-05-10 08:54:24.205258

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '258953be0f7e'
down_revision = 'd367b3e690be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Refills', 'amount',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Refills', 'amount',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
