"""'is_donatable' field added to Fundraise model.

Revision ID: 2b3f329f911f
Revises: 888efc5c543d
Create Date: 2022-07-01 12:03:00.217624

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2b3f329f911f'
down_revision = '888efc5c543d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fundraise_status_association_status_id_fkey', 'fundraise_status_association', type_='foreignkey')
    op.drop_constraint('fundraise_status_association_fundraise_id_fkey', 'fundraise_status_association', type_='foreignkey')
    op.create_foreign_key(None, 'fundraise_status_association', 'fundraise_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fundraise_status_association', 'fundraisers', ['fundraise_id'], ['id'], ondelete='CASCADE')
    op.add_column('fundraisers', sa.Column('is_donatable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraisers', 'is_donatable')
    op.drop_constraint(None, 'fundraise_status_association', type_='foreignkey')
    op.drop_constraint(None, 'fundraise_status_association', type_='foreignkey')
    op.create_foreign_key('fundraise_status_association_fundraise_id_fkey', 'fundraise_status_association', 'fundraisers', ['fundraise_id'], ['id'])
    op.create_foreign_key('fundraise_status_association_status_id_fkey', 'fundraise_status_association', 'fundraise_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###
