"""link users to balances

Revision ID: 6d776f76ce5e
Revises: 16f4b92ee598
Create Date: 2022-05-09 12:25:00.878604

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6d776f76ce5e'
down_revision = '16f4b92ee598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('balance_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'Users', 'Balances', ['balance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'balance_id')
    # ### end Alembic commands ###
