"""ChangePasswordToken model added.

Revision ID: 874af5e5e316
Revises: 5ec0f3ad9936
Create Date: 2022-05-26 09:18:29.008135

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '874af5e5e316'
down_revision = '5ec0f3ad9936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change-password-token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_change-password-token_id'), 'change-password-token', ['id'], unique=False)
    op.create_unique_constraint(None, 'CharityOrganisations', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CharityOrganisations', type_='unique')
    op.drop_index(op.f('ix_change-password-token_id'), table_name='change-password-token')
    op.drop_table('change-password-token')
    # ### end Alembic commands ###
