"""Cascade removing fundraisers when charity deleting.

Revision ID: 888efc5c543d
Revises: 532f289d1900
Create Date: 2022-06-30 10:23:39.957741

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '888efc5c543d'
down_revision = '532f289d1900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fundraisers_charity_id_fkey', 'fundraisers', type_='foreignkey')
    op.create_foreign_key(None, 'fundraisers', 'charities', ['charity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fundraisers', type_='foreignkey')
    op.create_foreign_key('fundraisers_charity_id_fkey', 'fundraisers', 'charities', ['charity_id'], ['id'])
    # ### end Alembic commands ###
