"""Charity and CharityUserAssociation models refactoring.

Revision ID: a1887f05fffb
Revises: 90c56cd024b2
Create Date: 2022-06-16 15:23:11.572323

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1887f05fffb'
down_revision = '90c56cd024b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=8192), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_charities_id'), 'charities', ['id'], unique=False)
    op.drop_index('ix_CharityOrganisations_id', table_name='CharityOrganisations')
    op.drop_constraint('charity_user_association_users_id_fkey', 'charity_user_association', type_='foreignkey')
    op.drop_constraint('charity_user_association_charity_id_fkey', 'charity_user_association', type_='foreignkey')
    op.drop_constraint('fundraisers_charity_id_fkey', 'fundraisers', type_='foreignkey')
    op.drop_table('CharityOrganisations')
    op.add_column('charity_user_association', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('charity_user_association', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('_charity_user_uc', 'charity_user_association', ['charity_id', 'user_id'])
    op.create_foreign_key(None, 'charity_user_association', 'Users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'charity_user_association', 'charities', ['charity_id'], ['id'])
    op.drop_column('charity_user_association', 'is_supermanager')
    op.drop_column('charity_user_association', 'users_id')
    op.drop_column('charity_user_association', 'is_director')
    op.create_foreign_key(None, 'fundraisers', 'charities', ['charity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fundraisers', type_='foreignkey')
    op.create_foreign_key('fundraisers_charity_id_fkey', 'fundraisers', 'CharityOrganisations', ['charity_id'], ['id'])
    op.add_column('charity_user_association', sa.Column('is_director', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('charity_user_association', sa.Column('users_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('charity_user_association', sa.Column('is_supermanager', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'charity_user_association', type_='foreignkey')
    op.drop_constraint(None, 'charity_user_association', type_='foreignkey')
    op.create_foreign_key('charity_user_association_charity_id_fkey', 'charity_user_association', 'CharityOrganisations', ['charity_id'], ['id'])
    op.create_foreign_key('charity_user_association_users_id_fkey', 'charity_user_association', 'Users', ['users_id'], ['id'])
    op.drop_constraint('_charity_user_uc', 'charity_user_association', type_='unique')
    op.drop_column('charity_user_association', 'created_at')
    op.drop_column('charity_user_association', 'user_id')
    op.create_table('CharityOrganisations',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('organisation_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='CharityOrganisations_pkey'),
    sa.UniqueConstraint('organisation_email', name='CharityOrganisations_organisation_email_key'),
    sa.UniqueConstraint('phone_number', name='CharityOrganisations_phone_number_key'),
    sa.UniqueConstraint('title', name='CharityOrganisations_title_key')
    )
    op.create_index('ix_CharityOrganisations_id', 'CharityOrganisations', ['id'], unique=False)
    op.drop_index(op.f('ix_charities_id'), table_name='charities')
    op.drop_table('charities')
    # ### end Alembic commands ###
