"""'etag' field added to UserPicture model.

Revision ID: c024e48ebc32
Revises: 6a176094c31c
Create Date: 2022-05-15 12:51:47.049903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c024e48ebc32'
down_revision = '6a176094c31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-pictures', sa.Column('etag', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-pictures', 'etag')
    # ### end Alembic commands ###
