"""EmailConfirmationToken table added + User table activated_at field

Revision ID: c8d4ed070b9f
Revises: c024e48ebc32
Create Date: 2022-05-18 18:17:14.465576

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8d4ed070b9f'
down_revision = 'c024e48ebc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email-confirmation-token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_email-confirmation-token_id'), 'email-confirmation-token', ['id'], unique=False)
    op.add_column('Users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.drop_column('Users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'activated_at')
    op.drop_index(op.f('ix_email-confirmation-token_id'), table_name='email-confirmation-token')
    op.drop_table('email-confirmation-token')
    # ### end Alembic commands ###
