"""link users to balances

Revision ID: d4111c8366d2
Revises: 6d776f76ce5e
Create Date: 2022-05-09 18:46:31.266553

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4111c8366d2'
down_revision = '6d776f76ce5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Refills',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('balance_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['Balances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Refills_id'), 'Refills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Refills_id'), table_name='Refills')
    op.drop_table('Refills')
    # ### end Alembic commands ###
