name: Dev checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: .env setup
        run: make env_setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./api_server/requirements.txt
      - name: Run flake8
        run: flake8 . --config ./api_server/.flake8
      - name: Run isort
        run: isort . --settings ./api_server/.isort.cfg --check
      - name: Run pytest
        run: make run_tests
